server:
  port: 10000

## TIPS: tx-service-group 一定要server，client都要保持一致
spring:
  application:
    name: fgd_seata_provider_app
  cloud:
    alibaba:
      seata:
        tx-service-group: fgd_seata_test_

  datasource:
    ds0:
      password: fangroot
      url: jdbc:mysql://localhost:3306/d_learn_dis_trans?ServerTimezone=GTM%2B8
      username: root
      driver-class-name: com.mysql.cj.jdbc.Driver
